Algoritmo "MeuNome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Escrever Bem-vindo e o nome da pessoa na tela
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/01/2022
Var
Nome: Caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Qual é seu nome?")
  leia(Nome)
  Escreva(" Bem-vindo ", Nome)

Fimalgoritmo